[package]
name = "bare_err_tree"
version = "0.1.0"
edition = "2021"

[features]
derive = ["dep:bare_err_tree_proc"]

[dependencies]
bare_err_tree_proc = { version = "0.1.0", path = "../proc", optional = true }
