[package]
name = "bare_err_tree"
version = "0.1.0"
edition = "2021"

[features]
default = ["derive"]
derive = ["dep:bare_err_tree_proc"]
heap_buffer = []

[dependencies]
bare_err_tree_proc = { version = "0.1.0", path = "../proc", optional = true }
