[package]
name = "std"
version = "0.1.0"
edition = "2021"

[dependencies]
bare_err_tree = { path = "../../", features = ["derive", "source_line"] }
thiserror = "2"

[[bin]]
name = "derive_testing"

[[bin]]
name = "example"

[[bin]]
name = "empty"

[[bin]]
name = "near-empty"
